### ISSUE TITLE
Fix ZZCatcher

### ISSUE THREAD

**Issue by tb0hdan** [tb0hdan/voiceplay#32]
`
02:52:49 [VoicePlay]> DEBUG:VoicePlay:LogOnlyPlayerHook.on_playback_start: args: () kwargs: {'path': '.cache/voiceplay/83dac8da44fcc5d0e5df2234b4be20680f62e683.mp3', 'track': 'We Will Rock Your'}
[0000000102c0c6b8] mpgatofixed32 audio converter error: libmad error: Huffman data overrun
[0000000102c0c6b8] mpgatofixed32 audio converter error: libmad error: Huffman data overrun
DEBUG:VoicePlay:Broken url None
DEBUG:VoicePlay:Method <bound method ScrobbleHook.on_playback_start of <class 'voiceplay.player.hooks.scrobble.ScrobbleHook'>> crashed (see message below), restarting...
Traceback (most recent call last):
  File "WRK/voiceplay/voiceplay/player/backend/vlc.py", line 118, in run_hooks
    method(*args, **kwargs)
  File "WRK/voiceplay/voiceplay/player/hooks/scrobble.py", line 54, in on_playback_start
    TrackScrobble.notify(*args, argparser=cls.argparser, **kwargs)
  File "WRK/voiceplay/voiceplay/player/hooks/scrobble.py", line 28, in notify
    title = track.split(' - ')[1]
IndexError: list index out of range
`

**Comment by tb0hdan** [comment]
Resolved in https://github.com/tb0hdan/voiceplay/commit/579778bf4c8bc09196533306c3aebc0170ce890a
